### ISSUE TITLE
space width difference between color and black on ios

### ISSUE THREAD

**Issue by Neutree** [victorqribeiro/imgToAscii#4]
**Describe the bug**

Space width difference between color and black on ios, color mode's width is shorter than black's

but it's normal on PC

**To Reproduce**
1. run server
2. open in ios's brower like Safari or Chrome
3. the space's width in color pic is wrong

**Expected behavior**

the shape of color's should be like black's

**Screenshots**

![5bc288075ed7048ee09d735422620e2](https://user-images.githubusercontent.com/8625829/90269655-87e56680-de8b-11ea-8035-deba52d3991e.jpg)

![d2882a4ac52fa2930695f1281d0c7ab](https://user-images.githubusercontent.com/8625829/90269746-b6634180-de8b-11ea-8f18-6932b3898ef3.jpg)

**Smartphone :**
 - Device:  iPhone11 pro
 - OS: iOS13.6
 - Browser:  Chrome, safari and Firefox all the same
 - Version: latest

**Comment by victorqribeiro** [comment]
Thank you for the bug report. This issue is now fixed.

**Comment by Neutree** [comment]
I made one converter page here https://neucrack.com/tools/ascii/ based on your code, it's nice~
thanks for your greate work!

**Comment by victorqribeiro** [comment]
Very nice. You're welcome!!!
